#!/usr/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down.sh /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/background.jpg --no-fehbg
fi
picom --config $SCRIPTPATH/picom.conf &
#polybar -c $SCRIPTPATH/polybar.ini workspace &
#polybar -c $SCRIPTPATH/polybar.ini title &
#polybar -c $SCRIPTPATH/polybar.ini infos &
